---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: infrastructure
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts

