---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - ../base/grafana-loki.yaml
  - ../base/kube-prometheus-stack.yaml
patchesStrategicMerge:
  - grafana-loki-values.yaml
  - kube-prometheus-stack-values.yaml

